name: Busine
favicon: null
layout_spectrum: 0
typography_spectrum: 0.89884
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.3125
  lightness: 0.8795003609266132
  saturation: 0.20385328400880098
  rhythmicContrast: 0.5161636960692704
purpose: []
